
package Tennis;
public class AddStudent extends java.awt.Dialog {
    private BinarySearchTree studentsTree;
    private boolean studentAdded = false;
    public AddStudent(java.awt.Frame parent, boolean modal, BinarySearchTree studentsTree)
    {
        super(parent, modal);
        initComponents();
        this.studentsTree = studentsTree;
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        nameLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        correctLabel = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        totalField = new javax.swing.JTextField();
        ageField = new javax.swing.JTextField();
        correctField = new javax.swing.JTextField();
        AddNewStudentTitle = new javax.swing.JLabel();
        AddNewStudentPicture = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();

        setModal(true);
        setResizable(false);
        setTitle("Add New Student");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        nameLabel.setText("Name:");
        jLayeredPane1.add(nameLabel);
        nameLabel.setBounds(130, 80, 90, 40);

        ageLabel.setText("Age:");
        jLayeredPane1.add(ageLabel);
        ageLabel.setBounds(130, 130, 50, 30);

        correctLabel.setText("Correct Answers: ");
        jLayeredPane1.add(correctLabel);
        correctLabel.setBounds(130, 160, 100, 40);

        totalLabel.setText("Total Questions:");
        jLayeredPane1.add(totalLabel);
        totalLabel.setBounds(130, 210, 130, 40);
        jLayeredPane1.add(nameField);
        nameField.setBounds(200, 90, 160, 22);
        jLayeredPane1.add(totalField);
        totalField.setBounds(230, 220, 160, 22);

        ageField.setText("");
        jLayeredPane1.add(ageField);
        ageField.setBounds(190, 140, 160, 22);
        jLayeredPane1.add(correctField);
        correctField.setBounds(230, 170, 160, 22);

        AddNewStudentTitle.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        AddNewStudentTitle.setText("Add New Student");
        jLayeredPane1.add(AddNewStudentTitle);
        AddNewStudentTitle.setBounds(60, 20, 200, 50);

        AddNewStudentPicture.setText("PICTURE");
        jLayeredPane1.add(AddNewStudentPicture);
        AddNewStudentPicture.setBounds(290, 20, 70, 40);

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    closeButtonActionPerformed(evt);
                }
            });
            jLayeredPane1.add(closeButton);
            closeButton.setBounds(90, 260, 72, 23);

            saveButton.setText("Save");
            saveButton.addActionListener(new java.awt.event.ActionListener()
                {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        saveButtonActionPerformed(evt);
                    }
                });
                jLayeredPane1.add(saveButton);
                saveButton.setBounds(230, 260, 72, 23);

                add(jLayeredPane1, java.awt.BorderLayout.CENTER);

                pack();
            }// </editor-fold>//GEN-END:initComponents
        private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) 
        {
        setVisible(false);
        dispose();
        }
        private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {
        if (validateInputs()) {
            String name = nameField.getText().trim();
            int age = Integer.parseInt(ageField.getText().trim());
            int correct = Integer.parseInt(correctField.getText().trim());
            int total = Integer.parseInt(totalField.getText().trim());
            
            // Check for duplicates
            Student tempStudent = new Student(name, age, 0, 0);
            if (studentsTree.contains(tempStudent)) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Error: Student with this name and age already exists!", 
                    "Duplicate Student", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Create and add student
            Student newStudent = new Student(name, age, correct, total);
            if (studentsTree.add(newStudent)) {
                studentAdded = true;
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Student added successfully!", 
                    "Success", 
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
                dispose();
            }
        }
    }

    private boolean validateInputs() {
        // Name validation
        if (nameField.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Name cannot be empty!", "Validation Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            nameField.requestFocus();
            return false;
        }
        
        if (!Validation.isValidName(nameField.getText().trim())) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Invalid name format!", "Validation Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            nameField.requestFocus();
            return false;
        }

        // Age validation
        if (!Validation.isInteger(ageField.getText().trim(), 1, 150)) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Age must be a number between 1 and 150!", "Validation Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            ageField.requestFocus();
            return false;
        }

        // Correct answers validation
        if (!Validation.isInteger(correctField.getText().trim(), 0, 1000)) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Correct answers must be a valid number!", "Validation Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            correctField.requestFocus();
            return false;
        }

        // Total questions validation
        if (!Validation.isInteger(totalField.getText().trim(), 0, 1000)) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Total questions must be a valid number!", "Validation Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            totalField.requestFocus();
            return false;
        }
        int correct = Integer.parseInt(correctField.getText().trim());
        int total = Integer.parseInt(totalField.getText().trim());
    
         if (correct < 0 || correct > total) {
        // Show the exact error dialog from your reference image
        javax.swing.JOptionPane.showMessageDialog(this,
            "Number of answers must be in the range [0, " + total + "].",
            "Range Error", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
        correctField.requestFocus();
        correctField.selectAll();
        return false;
    }

        return true;
    }

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    public boolean isStudentAdded()
    {
        return studentAdded;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BinarySearchTree testTree = new BinarySearchTree();
                AddStudent dialog = new AddStudent(new java.awt.Frame(), true, testTree);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddNewStudentPicture;
    private javax.swing.JLabel AddNewStudentTitle;
    private javax.swing.JTextField ageField;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JButton closeButton;
    private javax.swing.JTextField correctField;
    private javax.swing.JLabel correctLabel;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField totalField;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
