package Tennis;

public class StudentDetails extends javax.swing.JDialog {
    private Student student;
    public StudentDetails(java.awt.Frame parent, boolean modal, Student student) 
    {
        super(parent, modal);
        initComponents();
        this.student = student;
        displayStudentData();
        setLocationRelativeTo(parent);
    }
    private void displayStudentData()
    {
        if (student != null)
        {
            titleLabel.setText(student.getName() + " Details");
            double percent = student.calculatePercent();
            String details = String.format("Player: %s%nAge of player: %d%nCorrect answers: %d%nOut of total: %d%nPerecentage correct:  %.1f%%.", 
                    student.getName(),
                    student.getAge(),
                    student.getCorrect(),
                    student.getTotalQuestions(),
                    percent
            
            );
            detailsTextArea.setText(details);
        } 
        else 
        {
            detailsTextArea.setText("No Student Data found");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        closeButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        detailsTextArea = new javax.swing.JTextArea();

        setModal(true);
        setPreferredSize(new java.awt.Dimension(400, 350));
        setResizable(false);
        setTitle("Student Details");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(400, 300));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        setTitle("Student Details");
        setResizable(false);
        titleLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Student Details");
        jLayeredPane1.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(380, 220));

        detailsTextArea.setEditable(false);
        detailsTextArea.setColumns(30);
        detailsTextArea.setLineWrap(true);
        detailsTextArea.setRows(10);
        detailsTextArea.setWrapStyleWord(true);
        detailsTextArea.setFocusable(false);
        jScrollPane1.setViewportView(detailsTextArea);

        jLayeredPane1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 200, 100));

        add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Student testStudent = new Student("Rafael Carrero", 23, 2, 2);
                StudentDetails dialog = new StudentDetails(new java.awt.Frame(), true, testStudent);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JTextArea detailsTextArea;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
