/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package Tennis;

import javax.swing.ImageIcon;

public class TennisPlayerDetails extends java.awt.Dialog {
    private TennisPlayer player;
    public TennisPlayerDetails(java.awt.Frame parent, boolean modal, TennisPlayer player) 
    {
    super(parent, modal);
    this.player = player;
    initComponents();
    loadPlayerData();
    setLocationRelativeTo(parent);
    }

    private void loadPlayerData()
    {
        setTitle("Details for " + player.getName());
        playerNameLabel.setText(player.getName());
        loadFlagImage();
        String details = String.format
        (
        "Name: %s\nCountry: %s\nAge: %d\nEmail: %s\nPhone number: %s\nRank: %s",
        player.getName(),
        player.getCountry(), 
        player.getAge(),
        player.getEmail(),
        player.getPhone(),
        player.getRank()
        );
        detailsTextArea.setText(details);
    }
    private void loadFlagImage()
    {
        try
        {
            String country = player.getCountry();
            String flagPath = "Flags/" + country + ".jpg";
            ImageIcon flagIcon = new ImageIcon(flagPath);
                        // Check if image loaded successfully
            if (flagIcon.getIconWidth() > 0) {
                flagLabel.setIcon(flagIcon);
                flagLabel.setText(""); // Clear any placeholder text
            } else {
                // If PNG not found, try JPG
                flagPath = "Flags/" + country + ".jpg";
                flagIcon = new ImageIcon(flagPath);
                if (flagIcon.getIconWidth() > 0) {
                    flagLabel.setIcon(flagIcon);
                    flagLabel.setText("");
                } else {
                    flagLabel.setIcon(null);
                    flagLabel.setText("Flag not found");
                }
            }
        } catch (Exception e) {
            flagLabel.setIcon(null);
            flagLabel.setText("Flag error");
        }
    }

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt)
    {
        setVisible(false);
        dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        playerNameLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        detailsTextArea = new javax.swing.JTextArea();
        closeButton = new javax.swing.JButton();
        flagLabel = new javax.swing.JLabel();

        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        playerNameLabel.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        playerNameLabel.setForeground(new java.awt.Color(51, 51, 255));
        playerNameLabel.setText("PLAYER NAME");
        jLayeredPane1.add(playerNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 300, 80));

        detailsTextArea.setEditable(false);
        detailsTextArea.setBackground(new java.awt.Color(255, 255, 255));
        detailsTextArea.setColumns(20);
        detailsTextArea.setLineWrap(true);
        detailsTextArea.setRows(5);
        detailsTextArea.setText("Name: \nCountry: \nAge: \nEmail: \nPhone: \nRank:");
        detailsTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(detailsTextArea);

        jLayeredPane1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 300, 160));

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        flagLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        flagLabel.setText("Loading flag");
        flagLabel.setBorder(javax.swing.BorderFactory.createTitledBorder("Country Flag"));
        jLayeredPane1.add(flagLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 16, 80, 70));

        add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    public static void main(String args[]) {
    System.out.println("Run TennisPlayersGUI instead!");
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JTextArea detailsTextArea;
    private javax.swing.JLabel flagLabel;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel playerNameLabel;
    // End of variables declaration//GEN-END:variables
    }
